# DynamicApronCLI.ps1
. "C:\Users\hmche\dynamicapronsite\Blocks\Block3.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block4.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block5.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block6.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block7.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block8.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block9.ps1"
. "C:\Users\hmche\dynamicapronsite\Blocks\Block10.ps1"
Write-Host "✅ Dynamic Apron CLI initialized"
Write-Host "Available commands:"
Write-Host "  Initialize-Block3"
Write-Host "  Render-Block3"
Write-Host "  Initialize-Block4"
Write-Host "  Render-Block4"
Write-Host "  Initialize-Block5"
Write-Host "  Render-Block5"
Write-Host "  Initialize-Block6"
Write-Host "  Render-Block6"
Write-Host "  Initialize-Block7"
Write-Host "  Render-Block7"
Write-Host "  Initialize-Block8"
Write-Host "  Render-Block8"
Write-Host "  Initialize-Block9"
Write-Host "  Render-Block9"
Write-Host "  Initialize-Block10"
Write-Host "  Render-Block10"
